Comment out deploy ci action

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -98,21 +98,21 @@ jobs:
           labels: ${{ steps.meta.outputs.labels }}
           cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
           cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
-  deploy:
-      if: github.ref == 'refs/heads/main'
-      name: Deploy app
-      needs: build
-      runs-on: ubuntu-latest
-      steps:
-      - name: Trigger deployment
-        run: |
-          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST ${{ secrets.WEBHOOK_URL }} \
-            -H "Content-Type: application/json" \
-            -H "X-Signature: ${{ secrets.WEBHOOK_SECRET }}" \
-            -d '{}')
-          if [ "$RESPONSE" -ne "200" ]
-          then
-            echo "Deployment failed with status ${RESPONSE}"
-            exit 1
-          fi
+  # deploy:
+  #     if: github.ref == 'refs/heads/main'
+  #     name: Deploy app
+  #     needs: build
+  #     runs-on: ubuntu-latest
+  #     steps:
+  #     - name: Trigger deployment
+  #       run: |
+  #         RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST ${{ secrets.WEBHOOK_URL }} \
+  #           -H "Content-Type: application/json" \
+  #           -H "X-Signature: ${{ secrets.WEBHOOK_SECRET }}" \
+  #           -d '{}')
+  #         if [ "$RESPONSE" -ne "200" ]
+  #         then
+  #           echo "Deployment failed with status ${RESPONSE}"
+  #           exit 1
+  #         fi
 
